#!/usr/bin/env bash
# test-consolidate.sh — deterministic quality gate for brain/bin/consolidate.mjs,
# the script half of /brain:consolidate (INNOV-288).
#
# The skill turns ONE named wiki-graph community into a synthesis draft. The LLM
# writes the prose; this script decides everything mechanical, and each rule
# below is a way a consolidate run silently goes wrong:
#
#   - a bare invocation must print usage, never process all 42/131 communities
#   - a community that already contains a synthesis note (bridges/ or meta/)
#     yields an AMENDMENT, not a duplicate: negative-controlled against a
#     fixture shaped like personal-brain community 10
#   - the filing hint follows the Top-files spread: >=2 repo dirs -> bridges/.
#     bridges/ and meta/ are NOT repo dirs, or one repo + its bridge misfiles
#   - a principle with no [[link]] to a member note is DROPPED from the draft
#   - a draft naming community_id(s) is refused: ids are re-minted on rebuild
#     (SPO-303), so that anchor rots
#   - contradiction findings land in a logs/ review queue
#   - zero writes outside wiki/_drafts/ + logs/; the stubs are never touched
#
# Every fixture runs LF and CRLF (the vault is autocrlf — SPO-346).
#
# Run:  bash tests/test-consolidate.sh   (from anywhere)
# No network, no real vault. Requires `node`.
set -uo pipefail

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$TEST_DIR/.." && pwd)"
CONSOLIDATE="$REPO_ROOT/brain/bin/consolidate.mjs"
# The script resolves the vault from these before cwd; an ambient BRAIN_ROOT
# would point every case at the developer's real vault.
unset BRAIN_ROOT CLAUDE_PROJECT_DIR

PASSED=0
FAILED=0

TMPROOT="$(mktemp -d)"
cleanup() { rm -rf "$TMPROOT" 2>/dev/null || true; }
trap cleanup EXIT

# ---------------------------------------------------------------- helpers ---

pass() { PASSED=$((PASSED + 1)); echo "PASS $1"; }

fail() {
  FAILED=$((FAILED + 1))
  echo "FAIL $1"
  shift
  local line
  for line in "$@"; do
    echo "     $line"
  done
}

assert_eq() { # name expected actual [evidence...]
  local name="$1" exp="$2" act="$3"
  shift 3
  if [[ "$exp" == "$act" ]]; then
    pass "$name"
  else
    fail "$name" "expected: [$exp]" "actual:   [$act]" "$@"
  fi
}

assert_has() { # name needle haystack
  if printf '%s\n' "$3" | grep -qF -- "$2"; then
    pass "$1"
  else
    fail "$1" "missing: [$2]" "in: [$3]"
  fi
}

assert_lacks() { # name needle haystack
  if printf '%s\n' "$3" | grep -qF -- "$2"; then
    fail "$1" "unexpected: [$2]" "in: [$3]"
  else
    pass "$1"
  fi
}

# Write stdin to $1, converting to CRLF when EOL=crlf.
put() {
  mkdir -p "$(dirname "$1")"
  if [[ "$EOL" == crlf ]]; then
    sed 's/$/\r/' >"$1"
  else
    cat >"$1"
  fi
}

note() { # path id
  put "$1" <<EOF
---
id: $2
tags: [volleyball]
confidence: medium
---

# $2
EOF
}

# Every file outside wiki/_drafts/ and logs/, with its checksum.
snapshot() {
  (cd "$1" && find . -type f ! -path './wiki/_drafts/*' ! -path './logs/*' | LC_ALL=C sort | while IFS= read -r f; do
    printf '%s %s\n' "$(cksum <"$f")" "$f"
  done)
}

# Fixture shaped like personal-brain community 10: two repo dirs plus the
# hand-written bridge note that already synthesizes them. Plus a single-repo
# community with no synthesis member (the negative control), and a one-repo +
# one-bridge community (the filing-hint trap).
mk_vault() {
  V="$TMPROOT/vault-$EOL"
  rm -rf "$V"
  mkdir -p "$V/wiki/_drafts" "$V/logs"
  note "$V/wiki/bridges/bridge-volleyball-domain-model.md" bridge-volleyball-domain-model
  note "$V/wiki/scoreboard-overlay/overlay-scoring.md" overlay-scoring
  note "$V/wiki/scoreboard-overlay/overlay-rotation.md" overlay-rotation
  note "$V/wiki/spike-legends/legends-rally.md" legends-rally
  note "$V/wiki/spike-legends/legends-set.md" legends-set
  note "$V/wiki/volleyball-stats/stats-sync.md" stats-sync
  note "$V/wiki/volleyball-stats/stats-queue.md" stats-queue
  C="$V/graphify-out/communities"
  put "$C/_COMMUNITY_Volleyball Domain.md" <<'EOF'
---
generated: true
generator: bin/build-community-notes.mjs
repo: graphify-out
community_ids: [10]
node_count: 12
aliases:
  - "_COMMUNITY_Volleyball Domain & Scoreboard Overlay"
members:
  - "Rally"
---

# Volleyball Domain

> Auto-generated stub for graph community "Volleyball Domain" (graphify-out). Do not hand-edit —
> regenerated by `bin/build-community-notes.mjs`. Source of truth: `graphify-out/graph.json`.

**Member nodes:** 12 across 5 files.

## Top files
- `wiki/spike-legends/legends-rally.md` (4 nodes)
- `wiki/scoreboard-overlay/overlay-scoring.md` (3 nodes)
- `spike-legends/legends-set.md` (2 nodes)
- `wiki/bridges/bridge-volleyball-domain-model.md` (2 nodes)
- `scoreboard-overlay/overlay-rotation.md` (1 nodes)

See [[GRAPH_REPORT]] for the full graph picture.
EOF
  put "$C/_COMMUNITY_Flutter Offline Sync.md" <<'EOF'
---
generated: true
community_ids: [9]
node_count: 5
---

# Flutter Offline Sync

## Top files
- `wiki/volleyball-stats/stats-sync.md` (3 nodes)
- `wiki/volleyball-stats/stats-queue.md` (2 nodes)
- `wiki/volleyball-stats/stats-gone.md` (1 nodes)

See [[GRAPH_REPORT]] for the full graph picture.
EOF
  put "$C/_COMMUNITY_Overlay Only.md" <<'EOF'
---
generated: true
community_ids: [11]
node_count: 4
---

# Overlay Only

## Top files
- `wiki/scoreboard-overlay/overlay-scoring.md` (3 nodes)
- `wiki/bridges/bridge-volleyball-domain-model.md` (1 nodes)

See [[GRAPH_REPORT]] for the full graph picture.
EOF
}

brief() { (cd "$V" && node "$CONSOLIDATE" --brief "$1" 2>&1); }
check() { (cd "$V" && node "$CONSOLIDATE" --check "$1" --community "$2" 2>&1); }

for EOL in lf crlf; do
  echo "== $EOL"
  mk_vault
  BEFORE="$(snapshot "$V")"

  # --- scope is required ------------------------------------------------------
  out="$(cd "$V" && node "$CONSOLIDATE" 2>&1)"; rc=$?
  assert_eq "[$EOL] bare invocation exits 2" 2 "$rc"
  assert_has "[$EOL] bare invocation prints usage" "usage:" "$out"
  assert_lacks "[$EOL] bare invocation processes nothing" "mode:" "$out"

  out="$(cd "$V" && node "$CONSOLIDATE" --all 2>&1)"; rc=$?
  assert_eq "[$EOL] --all exits 0" 0 "$rc"
  assert_eq "[$EOL] --all lists every community, sorted" \
    "$(printf 'Flutter Offline Sync\nOverlay Only\nVolleyball Domain')" "$out"

  out="$(brief 'No Such Community')"; rc=$?
  assert_eq "[$EOL] unknown community exits 1" 1 "$rc"

  # --- community 10: synthesis member => amend, cross-repo => bridges/ -------
  out="$(brief 'Volleyball Domain')"; rc=$?
  assert_eq "[$EOL] brief exits 0" 0 "$rc" "$out"
  assert_has "[$EOL] c10 proposes an amendment" "mode: amend" "$out"
  assert_has "[$EOL] c10 amends the bridge note" "amend: bridge-volleyball-domain-model" "$out"
  assert_has "[$EOL] c10 files to bridges/" "filing_hint: wiki/bridges/" "$out"
  assert_has "[$EOL] c10 counts two repo dirs" "repo_dirs: scoreboard-overlay spike-legends" "$out"
  assert_has "[$EOL] members resolve with or without a wiki/ prefix" \
    "$(printf 'member: legends-set\twiki/spike-legends/legends-set.md\t2')" "$out"
  assert_lacks "[$EOL] brief never surfaces a community id" "community_id" "$out"

  alias_out="$(brief 'volleyball domain & scoreboard overlay')"
  assert_eq "[$EOL] alias (any case) resolves the same stub" "$out" "$alias_out"

  # --- negative control: no synthesis member => new, one repo => its area ----
  out="$(brief 'Flutter Offline Sync')"
  assert_has "[$EOL] single-repo community is a new draft" "mode: new" "$out"
  assert_lacks "[$EOL] single-repo community has no amend target" "amend:" "$out"
  assert_has "[$EOL] single-repo community files to its repo" "filing_hint: wiki/volleyball-stats/" "$out"
  assert_has "[$EOL] a Top-files path gone from disk is reported" "missing: wiki/volleyball-stats/stats-gone.md" "$out"

  out="$(brief 'Overlay Only')"
  assert_has "[$EOL] one repo + a bridge note is not cross-repo" "filing_hint: wiki/scoreboard-overlay/" "$out"

  # --- --check: drop unlinked principles --------------------------------------
  D="$V/wiki/_drafts/volleyball-domain.md"
  put "$D" <<'EOF'
---
id: volleyball-domain
tags: [volleyball]
confidence: low
draft: true
amends: bridge-volleyball-domain-model
---

# Volleyball domain model

## Principles
- Rally scoring is the shared invariant. [[legends-rally]] [[overlay-scoring]]
- Rotation is computed, never stored.
  continuation of the unlinked principle
- Sync conflicts resolve server-side. [[stats-sync]]
- Sets are the unit of persistence. [[legends-set|sets]]

## Contradictions
- [[overlay-rotation]] says rotation is stored; [[legends-rally]] recomputes it.
EOF
  out="$(check "$D" 'Volleyball Domain')"; rc=$?
  assert_eq "[$EOL] check with drops exits 0" 0 "$rc" "$out"
  body="$(cat "$D")"
  assert_has "[$EOL] linked principle kept" "Rally scoring is the shared invariant" "$body"
  assert_has "[$EOL] aliased link to a member kept" "Sets are the unit of persistence" "$body"
  assert_lacks "[$EOL] unlinked principle dropped" "Rotation is computed" "$body"
  assert_lacks "[$EOL] its continuation line dropped too" "continuation of the unlinked" "$body"
  assert_lacks "[$EOL] principle linking only a NON-member dropped" "Sync conflicts" "$body"
  assert_has "[$EOL] drops are reported" "dropped: 2" "$out"
  assert_has "[$EOL] contradictions left in the draft" "says rotation is stored" "$body"
  if [[ "$EOL" == crlf ]]; then
    assert_eq "[$EOL] rewrite preserves CRLF" "$(wc -l <"$D" | tr -d ' ')" "$(grep -c $'\r$' "$D")"
  fi

  q="$(cat "$V"/logs/consolidate-*.md 2>/dev/null)"
  assert_has "[$EOL] contradiction queued in logs/" "says rotation is stored" "$q"
  assert_has "[$EOL] queue entry names its draft" "wiki/_drafts/volleyball-domain.md" "$q"

  # negative control: a clean draft is byte-identical after --check
  cp "$D" "$TMPROOT/clean"
  out="$(check "$D" 'Volleyball Domain')"; rc=$?
  assert_eq "[$EOL] clean draft check exits 0" 0 "$rc" "$out"
  assert_has "[$EOL] clean draft reports no drops" "dropped: 0" "$out"
  if cmp -s "$D" "$TMPROOT/clean"; then pass "[$EOL] clean draft untouched"; else fail "[$EOL] clean draft untouched"; fi

  # --- refusals --------------------------------------------------------------
  B="$V/wiki/_drafts/bad-id.md"
  put "$B" <<'EOF'
---
id: bad-id
confidence: low
draft: true
community_ids: [10]
---

## Principles
- Rally scoring is shared. [[legends-rally]]
EOF
  cp "$B" "$TMPROOT/bad"
  out="$(check "$B" 'Volleyball Domain')"; rc=$?
  assert_eq "[$EOL] community_ids anchor refused" 1 "$rc" "$out"
  assert_has "[$EOL] refusal names the rot path" "community_id" "$out"
  if cmp -s "$B" "$TMPROOT/bad"; then pass "[$EOL] refused draft untouched"; else fail "[$EOL] refused draft untouched"; fi

  put "$B" <<'EOF'
---
id: bad-conf
confidence: high
draft: true
---

## Principles
- Rally scoring is shared. [[legends-rally]]
EOF
  out="$(check "$B" 'Volleyball Domain')"; rc=$?
  assert_eq "[$EOL] non-low confidence refused" 1 "$rc" "$out"

  put "$B" <<'EOF'
---
id: all-unlinked
confidence: low
draft: true
---

## Principles
- Nothing here links a member.
EOF
  cp "$B" "$TMPROOT/bad"
  out="$(check "$B" 'Volleyball Domain')"; rc=$?
  assert_eq "[$EOL] draft with no linked principle refused" 1 "$rc" "$out"
  if cmp -s "$B" "$TMPROOT/bad"; then pass "[$EOL] all-unlinked draft untouched"; else fail "[$EOL] all-unlinked draft untouched"; fi

  T="$V/wiki/spike-legends/legends-set.md"
  out="$(check "$T" 'Volleyball Domain')"; rc=$?
  assert_eq "[$EOL] --check outside wiki/_drafts/ refused" 1 "$rc" "$out"

  # --- zero writes outside wiki/_drafts/ + logs/ ------------------------------
  assert_eq "[$EOL] nothing outside wiki/_drafts/ + logs/ changed" "$BEFORE" "$(snapshot "$V")"
done

echo
echo "passed: $PASSED  failed: $FAILED"
[[ "$FAILED" -eq 0 ]]
